### ISSUE TITLE
Browser back not working

### ISSUE THREAD

**Issue by tdamsma** [devoopsme/devoops#16]
First of all, thank you for the wonderful devoops theme! 

I noticed an issue that the browser back button doesn't work as expected when navigating the devoops dashboard. After pressing back, the url is updated as expected e.g.:http://devoops.me/themes/devoops/#ajax/ui_grid.html ==> http://devoops.me/themes/devoops/#ajax/dashboard.html
but the page contents is not updated. 

Tested on latest ie, chrome and firefox

**Comment by jwjcmw** [comment]
jblossomweb, any success providing your fix?

**Comment by g0dzill3r** [comment]
Here's a very simply way to fix it. A more robust solution would keep an actual history in memory and navigate that...

$(window).on ("hashchange", function (e) { 
  var url = window.location.hash.substring (1); 
  LoadAjaxContent (url); 
});
