### ISSUE TITLE
AutoComplete Values Filled In Inputs Shows the Bootstrap Validation Errors

### ISSUE THREAD

**Issue by mohamedmusthafac** [devoopsme/devoops#22]
If we fill out the input fields using autocomplete still it shows up the Bootstrap validation errors

For Example: though if the username is correct which i filled using autocomplete it still shows the error of the username validation

In forms_layouts.html under Validator Forms

**Comment by vsbhati** [comment]
hello everyone, i have same problem but did not get right answer from here !

As eg. I have four fields. if i click on submit button it 's shows validation error on every field. after that if i select drop down list than other 3 fields auto fill by ajax. but still they shows validation error untill i modify that fields. Please let me know there is any solution !!!
Thanks in advance.
![vaidation error](https://cloud.githubusercontent.com/assets/11207109/6387444/489f62f6-bdb1-11e4-93ba-fa0c648479b8.png)

**Comment by devoopsme** [comment]
Need learn api of bootstrapvalidator.
Maybe resetForm method help you.
http://formvalidation.io/api/#reset-form
Or maybe can use update-status method, for manually set 'field is valid'
http://formvalidation.io/api/#update-status

**Comment by vsbhati** [comment]
Thanks for your reply @devoopsme 
i got solution, when we fetch data by ajax than after fetching data we have to refresh validation  for particular field. Like :  
$('#add').bootstrapValidator('revalidateField', 'name');

it's revalidate that field and it's best solution. i got one thing that searching keyword comes with our experience.
thanks again.
