### ISSUE TITLE
Left side menu actives the dashboard after Refreshing though my current page is different

### ISSUE THREAD

**Issue by mohamedmusthafac** [devoopsme/devoops#23]
For Example:
If i am in the page "Data Tables"

-Tables
----Data Tables

The left side menu gets active and it highlights the "Data Tables" Page
But if i refresh the "Data Tables" page it should highlight the same "Data Tables" Page in left side menu  after Refreshing, but it is highlighting the Dashboard Page

Any way i corrected this issue in my project by getting the current link in jquery and adding the active class in css using jquery for Left Side Menu

**Comment by Manikanta1023** [comment]
Hi,

var ajax_url = location.hash.replace(/^#/, '');
	if (ajax_url.length < 1) {
		ajax_url = 'ajax/dashboard.html';
	}
i have used this ajax replace firefox working good, in chrome not working [ NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///D:/fastlane_erp/30-Aug/erp/ajax/charts_xcharts.html'.] this is my problem in google chrome please help me.

**Comment by nnmware** [comment]
Hi. If I right understanding and remember - only FF can work with Ajax and local files. For Chrome and IE you need upload project to remove server.

**Comment by Manikanta1023** [comment]
Tq nnmware..
