### ISSUE TITLE
datepicker changeXxxxxx colors

### ISSUE THREAD

**Issue by briansol** [devoopsme/devoops#30]
When using the changeMonth and changeYear options to display the quick select drop-downs, the output is white on white, and thus not able to be seen to the user unless hovered.

example use case:

function `AllTimePickers()` could contain a listener such as:

`$( "#mydatefield" ).datepicker({ changeMonth: true, changeYear: true });`

and it ends up looking like: 

![datepicker](https://cloud.githubusercontent.com/assets/5598104/5650431/5df0d296-966c-11e4-967b-8408b70978e9.png)

It appears none of the examples use those options, so it was likely missed.

**Comment by devoopsme** [comment]
Sorry, i can't answer. This may solve via documentation of jquery-ui styles.
