### ISSUE TITLE
Unresponsive UI

### ISSUE THREAD

**Issue by CyberianIce** [devoopsme/devoops#34]
##### Request causing this symptom is located in main js
/js/devoops.js:1150
<code>
		async: false
</code>

Switching this boolean to true actually can't solve the problem (in fact, nothing can return lost requests), but it helps a lot as at least let user interact with other UI elements, navigate away or send another XHR to call actions as logout for example.

**Comment by devoopsme** [comment]
We already have few questions, like - User load theme from local drive. Only Firefox can work correctly in this situation. 
Example of problem - https://code.google.com/p/chromium/issues/detail?id=40787
With async: true-  we can more quick answer to problem.
I.e.- 'Theme not work full', or 'All works, but main content isn't load'

And at normal website- all need work correctly. Or work all, or nothing work.
Sorry for bad English, hope you understand sense.

**Comment by CyberianIce** [comment]
Actually I was testing this solution in enterprise environment where this template is loaded with nw.js (node-webkit) from local drive as fully packed client app (executable), which, once loaded, communicate with server via XHRs. In this scenario, AJAX loading from local machine is possible because nw.js uses some sort of node.js http server with tiny memory footprint who can handle XHR with blazing speed. I was very pleased with speed of ajax-based UI, loading speed and overall responsiveness.

However, at some point I decided to extend our services to support web interface for classic browsers. Afterwards, this template introduced me to the endless nightmare.
