### ISSUE TITLE
Memleaks in demo

### ISSUE THREAD

**Issue by CyberianIce** [devoopsme/devoops#35]
There are memleaks present in demo all aroud, which will cause this template to consume all remaining free memory over time.

Source of this memory leaks is random data generator used to generate example data for chars and dashboard.

Another memleak source is present because of console logging every single generated value.

Even after purifying code of demos and unneeded console logs, resources used by real-time charts need to be freed at some point of time when old ones becomes unneeded in order to improve memory management.

**Comment by yahyaerturan** [comment]
+1



*Yahya A. ERTURAN*
Senior PHP Developer  *@* Vayes Web Software*p* +90 (212) 855-9404    *m* +90
(544) 658-3787
*e* yahya@vayes.net        *w* vayes.net <http://www.vayes.net/>
<https://www.facebook.com/vayeswebyazilim>
<https://www.linkedin.com/company/vayes-web-yazilim>
<https://github.com/yahyaerturan>  <https://twitter.com/vayeswebyazilim>
<https://plus.google.com/117415704592585673512/about>




On Thu, Oct 8, 2015 at 1:49 PM, Vladimir Radakovic <notifications@github.com

**Comment by devoopsme** [comment]
Sure. Demo charts, etc, using random generator.  
Console log- for better debugging.
It's not issue, if need  - you can disable logging and use real data for charts.
